apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service
  namespace: lugx-gaming
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-service
  template:
    metadata:
      labels:
        app: game-service
    spec:
      containers:
      - name: game-service
        image: gimgim/game-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
---
apiVersion: v1
kind: Service
metadata:
  name: game-service
  namespace: lugx-gaming
spec:
  selector:
    app: game-service
  ports:
  - port: 80
    targetPort: 3001
  type: LoadBalancer  # So you can access from outside