apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: lugx-gaming
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: gimgim/order-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: NODE_ENV
          value: production
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: lugx-gaming
spec:
  selector:
    app: order-service
  ports:
  - port: 80
    targetPort: 3002
  type: LoadBalancer  # So you can access from outside