## postgres.yaml (Corrected)

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: lugx-gaming
type: Opaque
data:
  # The base64 encoded version of "lugx_password"
  postgres-password: bHVneF9wYXNzd29yZA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: lugx-gaming
spec:
  replicas: 1
  # This selector was missing. It tells the Deployment which pods to manage.
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      # These labels were missing. They are applied to the pods.
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: lugx_gaming
        - name: POSTGRES_USER
          value: lugx_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: lugx-gaming
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432