apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: lugx-gaming
type: Opaque
data:
  password: bHVneF9wYXNzd29yZA==  # base64 of "lugx_password"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: lugx-gaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: lugx_gaming
        - name: POSTGRES_USER
          value: lugx_user
        - name: POSTGRES_PASSWORD
          value: lugx_password
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: lugx-gaming
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432